# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: fft-hs
version: '1.0.0'
github: "hg2ecz/ProgrammingLanguageBenchmark-FFT_4096"
license: MIT
author: "Róbert Fuszenecker"
maintainer: "Róbert Fuszenecker"
# synopsis: A new Haskeleton package.
# description: Haskell is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall -O

library:
  dependencies:
  - base
  - vector
  - primitive
  - time
  - async
  source-dirs: library
  ghc-options:
  - -O

executables:
  fft-hs:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - vector
    - primitive
    - time
    - async
    - fft-hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -O
    - -optl-static

tests:
  fft-hs-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - Haskell
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
