language: csharp
dist: xenial
mono: none
dotnet: 2.0.0

script:
  - cd C#
  - make -C ../C-fast-all-complex-float-types-opt-4x
  - dotnet restore
  - dotnet run -c Release
  - sh create-armhf-deb.sh

install:
  - sudo apt-get install -qq gcc-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
